log:
  level: info

plugins:
  # --- 1. 数据集---
  - tag: mainland_domain_set
    type: domain_set
    args:
      exps:
        - domain:cloudflareclient.com
        - domain:cloudflareaccess.com
        - domain:cloudflareportal.com
        - domain:cloudflareok.com
        - domain:cloudflarecp.com
        - domain:msftconnecttest.com
        - domain:apple.com
        - domain:gstatic.com
        - domain:cloudflare-gateway.com
        - domain:cloudflare-dns.com
        - domain:cloudflare.com
        - domain:argotunnel.com
        - domain:cftunnel.com
        - domain:cloudflareresearch.com
      files:
        - "./geosite_apple-cn.txt"
        - "./geosite_google-cn.txt"

  - tag: overseas_domain_set
    type: domain_set
    args:
      files:
        - "./geosite_overseas.txt"

  - tag: ads_domain_set
    type: domain_set
    args:
      files:
        - "./geosite_category-ads-all.txt"

  # --- 2. 缓存：乐观缓存 ---
  - tag: main_cache
    type: cache
    args:
      size: 4096
      lazy_cache_ttl: 259200

  # --- 3. 国内域名解析 ---
  - tag: mainland_forward_udp
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "119.29.29.29"
        - addr: "119.28.28.28"
        - addr: "223.5.5.5"
        - addr: "223.6.6.6"
        - addr: "114.114.114.114"
        - addr: "114.114.115.115"

  - tag: mainland_forward_dot
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "tls://223.5.5.5:853"
        - addr: "tls://223.6.6.6:853"

  - tag: mainland_forward_direct
    type: fallback
    args:
      primary: mainland_forward_udp
      secondary: mainland_forward_dot
      threshold: 500

  # --- 4. PTR反向解析 ---
  - tag: redirect_to_local_ptr
    type: redirect
    args:
      rules:
        - domain:in-addr.arpa. dns.lan
        - domain:ip6.arpa. dns.lan
        - domain:127.in-addr.arpa. localhost
        - full:1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa. localhost

  - tag: static_ptr_answer
    type: arbitrary
    args:
      rules:
        - 'localhost. 86400 IN PTR localhost.'
        - 'dns.lan. 86400 IN PTR \206\210\176\174\196\227.' #无聊显示为”我爱你”

  - tag: ptr_handler_sequence
    type: sequence
    args:
      - exec: $redirect_to_local_ptr
      - exec: $static_ptr_answer

  # --- 5. Google DoH (通过代理) ---
  - tag: overseas_forward_proxy
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8:443"
          bootstrap: "223.5.5.5"
          bootstrap_version: 4
          socks5: "127.0.0.1:40000"
          enable_pipeline: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8:443"
          bootstrap: "223.6.6.6"
          bootstrap_version: 4
          socks5: "127.0.0.1:40000"
          enable_pipeline: true

  # --- 6. 核心执行序列 (Sequence) ---
  - tag: main_sequence
    type: sequence
    args:
      # 6.1 查缓存
      - exec: $main_cache
      - matches: has_resp
        exec: accept
      # 6.2 匹配IP反向查询
      - matches: ptr_ip 127.0.0.0/8 10.0.0.0/8 192.168.0.0/16 172.16.0.0/12 ::1/128 fc00::/7 fe80::/10
        exec: $ptr_handler_sequence
      - matches: has_resp
        exec: accept
      # 6.3 匹配广告域名  
      - matches: qname $ads_domain_set
        exec: black_hole 127.0.0.1 ::1 0.0.0.0
      - matches: has_resp
        exec: accept
      # 6.4 自举域名优先由境内DNS解析
      - matches: qname $mainland_domain_set
        exec: $mainland_forward_direct
      - matches: has_resp
        exec: accept
      # 6.5 境外由dns.google doh解析
      - matches: qname $overseas_domain_set
        exec: $overseas_forward_proxy
      - matches: has_resp
        exec: accept
      # 6.6 默认由境内DNS解析
      - exec: $mainland_forward_direct 

  # --- 7. 服务器入口 ---

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":53"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":53"
