name: Build Mosdns Domain Lists

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Download geosite.dat
        run: |
          wget -O geosite.dat https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat

      - name: Prepare mosdns
        run: |
          chmod +x tools/mosdns

      - name: Prepare output directory
        run: |
          mkdir -p output

      - name: Extract domain lists
        run: |
          ./tools/mosdns v2dat unpack-domain -o ./output geosite.dat:cn
          mkdir -p tmp
          ./tools/mosdns v2dat unpack-domain -o ./tmp geosite.dat:geolocation-!cn
          mv ./tmp/*.txt ./output/geosite_overseas.txt
          ./tools/mosdns v2dat unpack-domain -o ./output geosite.dat:category-ads-all
          ./tools/mosdns v2dat unpack-domain -o ./output geosite.dat:china-list
          ./tools/mosdns v2dat unpack-domain -o ./output geosite.dat:apple-cn
          ./tools/mosdns v2dat unpack-domain -o ./output geosite.dat:google-cn
          rm -rf tmp

      - name: Show output files
        run: |
          ls -lah output

      - name: Create/Update Release (latest)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Mosdns Domain Lists
          make_latest: true
          overwrite: true
          files: |
            output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
